APPLICATION=shell

BOARD ?= pba-d-01-kw2x

RIOTBASE ?= $(CURDIR)/../../../../RIOT

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += mpl3115a2

include $(RIOTBASE)/Makefile.include
